#!/usr/bin/env python3
"""Generate the search-only character table from a pinned OpenCC dictionary."""
import hashlib
import json
from pathlib import Path
import sys

REVISION = '3ac34aa439a9908dd49fa92b5174b46314787ac2'
SHA256 = '9ff46a7d30e5765375eb13d33f2b03a34d298913caf2b120380679f33ae1642d'
SOURCE = f'https://raw.githubusercontent.com/BYVoid/OpenCC/{REVISION}/data/dictionary/TSCharacters.txt'


def main():
    if len(sys.argv) != 2:
        raise SystemExit(f'Download {SOURCE}, then pass the file path to this script.')
    data = Path(sys.argv[1]).read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA256:
        raise SystemExit('Dictionary does not match the pinned OpenCC revision.')
    pairs = []
    for line in data.decode().splitlines():
        if not line or line.startswith('#'):
            continue
        source, candidates = line.split('\t')
        target = candidates.split()[0]
        if source == target:
            continue
        if len(source) != 1 or len(target) != 1:
            raise ValueError('Expected a character dictionary, not a phrase dictionary.')
        pairs.append(source + target)
    chunks = [json.dumps(''.join(pairs[i:i + 40]), ensure_ascii=False) for i in range(0, len(pairs), 40)]
    generated = f'''// Generated by scripts/generate_search_characters.py; do not edit by hand.
// OpenCC / BYVoid and contributors, Apache-2.0; see licenses/OpenCC.txt.
// Source: {SOURCE}
// SHA-256: {SHA256}
// Default character candidates only; not a phrase/translation converter.
const pairs =
  ''' + ' +\n  '.join(chunks) + ''';
const characters = [...pairs], substitutions = new Map();
for (let i = 0; i < characters.length; i += 2) substitutions.set(characters[i], characters[i + 1]);

// Search presentation only. Never rewrite stored titles or library identities.
export function simplifySearchText(value) {
  return [...value].map(char => substitutions.get(char) || char).join('');
}
'''
    target = Path(__file__).resolve().parents[1] / 'web/search-characters.js'
    target.write_text(generated)
    print(f'Generated {len(pairs)} character pairs in {target.name}.')


if __name__ == '__main__':
    main()
